# Generated by Django 4.2.10 on 2024-02-22 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_msg_id', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MSG', 'Message'), ('FILE', 'File')], max_length=20)),
                ('text', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
