# Generated by Django 4.2.10 on 2024-02-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_flaggedmessage_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedmessage',
            name='ts',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='client_msg_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
